name: dixlearning
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_animate: ^4.5.0
  audioplayers: ^5.2.1
  provider: ^6.0.5
  fluentui_system_icons: ^1.1.217
  flutter_switch: ^0.3.2
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  flutter_tts: ^3.7.0 # <-- TTS paketi eklendi
  confetti: ^0.7.0 # <-- Konfeti efekti için

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/giris/disgrafi1/ses1.mp3
    - assets/giris/disgrafi1/ses2.mp3
    - assets/asama3/
    - assets/asama3/soru1/block_tower.png
    - assets/asama3/soru1/finger_painting.png
    - assets/asama3/soru1/kicking_ball.png
    - assets/asama2_soru2/kurbagarenkli.png
    - assets/asama2_soru2/kurbagagolge.png
    - assets/asama2_soru2/golgepantalon.png
    - assets/asama2_soru2/pantalonrenkli.png
    - assets/asama2_soru2/yedigolge.png
    - assets/asama2_soru2/yedirenkli.png
    - assets/erkek_maskot.png
    - assets/kiz_maskot.png
    - assets/konusma_balonu.png
    - assets/SIRALAMA_RESIMLERI/
    
    # Az-Çok Karşılaştırma
    - assets/az_cok_asa1/soru1/
    - assets/az_cok_asa1/soru2/
    - assets/az_cok_asa1/soru3/
    - assets/az_cok_asa1/soru4/
    - assets/az_cok_asa1/soru5/
    - assets/az_cok_asa1/soru6/
    - assets/az_cok_asa1/soru7/
    - assets/az_cok_asa1/soru8/
    - assets/az_cok_asa1/soru9/
    
    # Uzun-Kısa Karşılaştırma
    - assets/uzun_kisa/soru1/
    - assets/uzun_kisa/soru2/
    - assets/uzun_kisa/soru3/
    - assets/uzun_kisa/soru4/
    - assets/uzun_kisa/soru5/
    - assets/uzun_kisa/soru6/
    - assets/uzun_kisa/soru7/
    - assets/uzun_kisa/soru8/
    - assets/uzun_kisa/soru9/
    
    - assets/buyuk_kucuk/soru1/Resim1.png
    - assets/buyuk_kucuk/soru2/Resim2.png
    - assets/buyuk_kucuk/soru3/Resim3.png
    - assets/buyuk_kucuk/soru4/Resim4.png
    - assets/buyuk_kucuk/soru5/Resim5.png
    - assets/buyuk_kucuk/soru6/Resim6.png
    - assets/buyuk_kucuk/soru7/Resim7.png
    - assets/buyuk_kucuk/soru8/Resim8.png
    - assets/buyuk_kucuk/soru9/Resim9.png
    - assets/SIRALAMA_RESIMLERI/Asama2/soru1/aksam.png
    - assets/SIRALAMA_RESIMLERI/Asama2/soru1/gun_dogumu.png
    - assets/SIRALAMA_RESIMLERI/Asama2/soru1/gunes_tepede.png
    - assets/SIRALAMA_RESIMLERI/Asama2/soru2/corba.png
    - assets/SIRALAMA_RESIMLERI/Asama2/soru2/kurabiye.png
    - assets/SIRALAMA_RESIMLERI/Asama2/soru2/dondurma.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru1/tohum.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru1/filiz.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru1/cicekli_agac.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru1/agac.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru2/yumurta.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru2/yumurta_civciv.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru2/civciv.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru2/tavuk.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru3/iki_isirikli_elma.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru3/butun_elma.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru3/bitmis_elma.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru3/bir_isirikli_elma.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru4/malzemeler.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru4/kek.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru4/hamur.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru4/firin.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru5/yetiskin.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru5/yasli.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru5/cocuk.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru5/bebek.png
    - assets/siniflama1/
    - assets/siniflama2/
    - assets/buyuk_kucuk/
    - assets/kalin_ince_asa1/
    - assets/kalin_ince_asa1/soru1/Resim1.png
    - assets/kalin_ince_asa1/soru1/Resim2.png
    - assets/kalin_ince_asa1/soru2/Resim3.png
    - assets/kalin_ince_asa1/soru2/Resim4.png
    - assets/kalin_ince_asa1/soru3/Resim5.png
    - assets/kalin_ince_asa1/soru3/Resim6.png
    - assets/kalin_ince_asa1/soru4/Resim7.png
    - assets/kalin_ince_asa1/soru4/Resim8.png
    - assets/kalin_ince_asa1/soru5/Resim9.png
    - assets/kalin_ince_asa1/soru5/Resim10.png
    - assets/kalin_ince_asa1/soru6/Resim11.png
    - assets/kalin_ince_asa1/soru6/Resim12.png
    - assets/kalin_ince_asa1/soru7/Resim13.png
    - assets/kalin_ince_asa1/soru7/Resim14.png
    - assets/kalin_ince_asa1/soru8/Resim15.png
    - assets/kalin_ince_asa1/soru8/Resim16.png
    - assets/kalin_ince_asa1/soru9/Resim17.png
    - assets/kalin_ince_asa1/soru9/Resim18.png
    - assets/kalin_ince_asa1/
    - assets/SIRALAMA_RESIMLERI/Asama2/soru1/aksam.png
    - assets/SIRALAMA_RESIMLERI/Asama2/soru1/gunes_tepede.png
    - assets/SIRALAMA_RESIMLERI/Asama2/soru1/gun_dogumu.png
    - assets/SIRALAMA_RESIMLERI/Asama2/soru2/corba.png
    - assets/SIRALAMA_RESIMLERI/Asama2/soru2/kurabiye.png
    - assets/SIRALAMA_RESIMLERI/Asama2/soru2/dondurma.png
    - assets/SIRALAMA_RESIMLERI/Asama2/soru3/eve_yakın.png
    - assets/SIRALAMA_RESIMLERI/Asama2/soru3/evden_uzak.png
    - assets/SIRALAMA_RESIMLERI/Asama2/soru3/evden_en_uzak.png
    - assets/SIRALAMA_RESIMLERI/Asama2/soru4/ucak_pistte.png
    - assets/SIRALAMA_RESIMLERI/Asama2/soru4/ucak_kalkısta.png
    - assets/SIRALAMA_RESIMLERI/Asama2/soru4/ucan_ucak.png
    - assets/SIRALAMA_RESIMLERI/Asama2/soru5/rüzgar.png
    - assets/SIRALAMA_RESIMLERI/Asama2/soru5/ucan_sapka.png
    - assets/SIRALAMA_RESIMLERI/Asama2/soru5/sapka_yakalama.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru1/tohum.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru1/filiz.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru1/cicekli_agac.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru1/agac.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru2/yumurta.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru2/yumurta_civciv.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru2/civciv.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru2/tavuk.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru3/iki_isirikli_elma.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru3/butun_elma.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru3/bitmis_elma.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru3/bir_isirikli_elma.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru4/malzemeler.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru4/kek.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru4/hamur.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru4/firin.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru5/yetiskin.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru5/yasli.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru5/cocuk.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru5/bebek.png
    - assets/SIRALAMA_RESIMLERI/Asama4/elyikama/
    - assets/SIRALAMA_RESIMLERI/Asama4/disfirca/
    - assets/SIRALAMA_RESIMLERI/Asama4/tirnak/
    - assets/SIRALAMA_RESIMLERI/Asama4/ayakkabi/
    - assets/SIRALAMA_RESIMLERI/Asama4/giyinme/
    - assets/siniflama1/
    - assets/siniflama2/
    - assets/kalin_ince_asa1/
    - assets/screensphoto/
    - assets/popup/
  

    