name: dixlearning
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_animate: ^4.5.0
  audioplayers: ^5.2.1
  provider: ^6.0.5
  fluentui_system_icons: ^1.1.217
  flutter_switch: ^0.3.2
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/giris/disgrafi1/ses1.mp3
    - assets/giris/disgrafi1/ses2.mp3
    - assets/asama3/soru1/block_tower.png
    - assets/asama3/soru1/finger_painting.png
    - assets/asama3/soru1/kicking_ball.png
    - assets/erkek_maskot.png
    - assets/kiz_maskot.png
    - assets/konusma_balonu.png
    - assets/az_cok_asa1/
    - assets/uzun_kisa/
    - assets/buyuk_kucuk/
    - assets/kalin_ince_asa1/
    - assets/SIRALAMA_RESIMLERI/Asama3/soru1/tohum.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru1/filiz.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru1/cicekli_agac.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru1/agac.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru2/yumurta.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru2/yumurta_civciv.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru2/civciv.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru2/tavuk.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru3/iki_isirikli_elma.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru3/butun_elma.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru3/bitmis_elma.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru3/bir_isirikli_elma.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru4/malzemeler.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru4/kek.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru4/hamur.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru4/firin.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru5/yetiskin.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru5/yasli.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru5/cocuk.png
    - assets/SIRALAMA_RESIMLERI/Asama3/soru5/bebek.png
    - assets/siniflama1/

    
